version: 1.0.{build}
image: Visual Studio 2015

build: off

environment:
  global:
    # Avoid long paths on Windows
    STACK_ROOT: "c:\\s"
    STACK_WORK: ".w"
    WORK_DIR: "c:\\m"
  matrix:
  - RESOLVER: "lts-12.26"
    STACK_YAML: "stack-extra-deps.yaml"
  - RESOLVER: "lts-13.30"
    STACK_YAML: "stack-extra-deps.yaml"
  - RESOLVER: "lts-14.27"
    STACK_YAML: "stack-extra-deps.yaml"
  - RESOLVER: "lts-15"
    STACK_YAML: "stack-extra-deps.yaml"
  - RESOLVER: "nightly"
matrix:
  allow_failures:
    - RESOLVER: "nightly"

init:
  - SET WORK_DIR_NO_PR=%WORK_DIR%\%APPVEYOR_REPO_BRANCH%
  - SET STACK_ROOT_NO_PR=%STACK_ROOT%\%APPVEYOR_REPO_BRANCH%
  - SET WORK_DIR=%WORK_DIR%\%APPVEYOR_PULL_REQUEST_NUMBER%\%APPVEYOR_REPO_BRANCH%\
  - SET STACK_ROOT=%STACK_ROOT%\%APPVEYOR_PULL_REQUEST_NUMBER%\%APPVEYOR_REPO_BRANCH%\
  - SET ARGS="--resolver %RESOLVER%"
  - SET BUILD_ARGS="-j 2 --no-terminal --bench --no-run-benchmarks --haddock --no-haddock-deps"

cache:
- "%STACK_ROOT_NO_PR%"
- "%WORK_DIR_NO_PR%\\massiv-io\\%STACK_WORK%"
- "%LOCALAPPDATA%\\Programs\\stack"

before_test:
- curl -s -L https://gist.githubusercontent.com/lehins/fd36a8cc8bf853173437b17f6b6426ad/raw/d127fe35bc6dc0b8fa69767a4ec13c1bfffe4fa7/git-modtime.hs -o git-modtime.hs
- stack script --resolver %RESOLVER% git-modtime.hs
# Avoid long paths not to each MAX_PATH of 260 chars
- xcopy /q /s /e /r /k /i /v /h /y C:\projects\massiv-io "%WORK_DIR%"
- cd "%WORK_DIR%"
# Setup cache dirs
# Debug paths
- Echo WORK_DIR = %WORK_DIR%
- dir %WORK_DIR%
- Echo STACK_ROOT = %STACK_ROOT%


# Install stack
- curl -sSkL https://www.stackage.org/stack/windows-x86_64 -o stack.zip
- 7z x stack.zip stack.exe -aoa

test_script:
  - cd "%WORK_DIR%"
  - stack %ARGS% --verbosity warn setup --no-reinstall > nul
  - stack %ARGS% test massiv-io:tests %BUILD_ARGS%
  - stack %ARGS% test massiv-io:doctests %BUILD_ARGS%


notifications:
  - provider: Email
    to:
      - alexey@kuleshevi.ch
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
