resolver: lts-15.2
packages:
- 'massiv-io/'
flags: {}
extra-package-dbs: []
extra-deps:
# - Color-0.2.0@sha256:94c43c4d8f943ba0642ee58a9b8a665b01a3ac2893c40a16ffdabaacb956c58f,8159
# - massiv-0.5.2.0
# - massiv-0.1.3
- github: lehins/Color
  commit: 7fccb49eee6f3ec44dfc6da99e0c14e884ed8ecf
  subdirs:
    - Color

