resolver: lts-15.2
packages:
- 'massiv-io/'
flags: {}
extra-package-dbs: []
extra-deps:
#- Color-0.1.4
- github: lehins/Color
  commit: c566a3083a238eba70e61ba0e261f9dacb8481bb
  subdirs:
    - Color
