resolver: lts-15.2
packages:
- 'massiv-io/'
flags: {}
extra-package-dbs: []
extra-deps:
#- Color-0.2.0
- github: lehins/Color
  commit: 6a3932da974132a5ec87f7f97237e9e659f53e48
  subdirs:
    - Color
