parameters:
- name: setupEnvironmentSteps
  displayName: 'Setup stack and all other pre-build stuff'
  type: stepList
  default: []
- name: jobName
  type: string
- name: vmImage
  type: string
- name: os
  type: string
- name: stackRoot
  default: "$(System.DefaultWorkingDirectory)/.stack"
- name: stackWork
  default: ".stack-work"
- name: stackWorkFull
  default: "$(Build.SourcesDirectory)/massiv-io/${{ parameters.stackWork }}"

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  variables:
    STACK_ROOT: "${{ parameters.stackRoot }}"
    STACK_WORK: "${{ parameters.stackWork }}"
    STACK_WORK_FULL: "${{ parameters.stackFullWork }}"
    BUILD_ARGS: "-j 2 --no-terminal --bench --no-run-benchmarks"
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      lts-12.26:
        RESOLVER: "lts-12.26"
        STACK_YAML: "stack-extra-deps.yaml"
      lts-13.30:
        RESOLVER: "lts-13.30"
        STACK_YAML: "stack-extra-deps.yaml"
      lts-14.27:
        RESOLVER: "lts-14.27"
        STACK_YAML: "stack-extra-deps.yaml"
      lts-15:
        RESOLVER: "lts-15"
      nightly:
        RESOLVER: "nightly"
    maxParallel: 5
  steps:
  - task: Cache@2
    displayName: Cache STACK_ROOT
    inputs:
      key: '"${{ parameters.name }}" | "STACK_ROOT" | "$(RESOLVER) | $(Build.SourceBranch)"'
      path: "$(STACK_ROOT)"
      restoreKeys: |
        "${{ parameters.name }}" | "STACK_ROOT" | "$(RESOLVER) | $(Build.SourceBranch)"
        "${{ parameters.name }}" | "STACK_ROOT" | "$(RESOLVER) | refs/heads/master"
      cacheHitVar: STACK_ROOT_RESTORED
  - task: Cache@2
    displayName: Cache STACK_WORK
    inputs:
      key: '"${{ parameters.name }}" | "STACK_WORK" | "$(RESOLVER) | $(Build.SourceBranch)"'
      path: "$(STACK_WORK_FULL)"
      restoreKeys: |
        "${{ parameters.name }}" | "STACK_WORK" | "$(RESOLVER) | $(Build.SourceBranch)"
        "${{ parameters.name }}" | "STACK_WORK" | "$(RESOLVER) | refs/heads/master"
      cacheHitVar: STACK_WORK_RESTORED
  - ${{ each step in parameters.setupEnvironmentSteps }}:
    - ${{ each pair in step }}:
        ${{ pair.key }}: ${{ pair.value }}
  - task: Bash@3
    displayName: 'stack build'
    env:
      ARGS: "--resolver $(RESOLVER)"
    inputs:
      targetType: 'inline'
      script: |
        set -x
        ./stack ${ARGS} test --no-run-tests ${BUILD_ARGS} --haddock --no-haddock-deps
  - task: Bash@3
    displayName: 'massiv-io:test'
    env:
      ARGS: "--resolver $(RESOLVER)"
    inputs:
      targetType: 'inline'
      script: |
        set -x
        ./stack ${ARGS} test massiv-io:tests ${BUILD_ARGS}
  - task: Bash@3
    displayName: 'massiv-io:doctest'
    env:
      ARGS: "--resolver $(RESOLVER)"
    inputs:
      targetType: 'inline'
      script: |
        set -x
        ./stack ${ARGS} test massiv-io:doctests ${BUILD_ARGS}
