jobs:
# - template: ./osx.yml
#   parameters:
#     name: macOS
#     vmImage: macOS-10.13
#     os: osx

# - template: ./linux.yml
#   parameters:
#     name: Linux
#     vmImage: ubuntu-18.04
#     os: linux

- template: ./windows.yml
  parameters:
   name: Windows
   vmImage: vs2017-win2016
   os: windows
