jobs:
# - template: ./.azure/osx.yml
#   parameters:
#     name: macOS
#     vmImage: macOS-10.13
#     os: osx

# - template: ./.azure/linux.yml
#   parameters:
#     name: Linux
#     vmImage: ubuntu-18.04
#     os: linux

- template: ./.azure/windows.yml
  parameters:
   name: Windows
   vmImage: vs2017-win2016
   os: windows
