jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  variables:
    STACK_ROOT: "$(System.DefaultWorkingDirectory)\\s"
    STACK_WORK: ".w"
    STACK_WORK_FULL: "$(Build.SourcesDirectory)\\$(STACK_WORK)"
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      lts-12.26:
        RESOLVER: "lts-12.26"
        STACK_YAML: "stack-extra-deps.yaml"
      lts-13.30:
        RESOLVER: "lts-13.30"
        STACK_YAML: "stack-extra-deps.yaml"
      lts-14.27:
        RESOLVER: "lts-14.27"
        STACK_YAML: "stack-extra-deps.yaml"
      lts-15:
        RESOLVER: "lts-15"
      nightly:
        RESOLVER: "nightly"
    maxParallel: 5
  steps:
  - bash: |
      mkdir -p "${STACK_ROOT}"
      mkdir -p "${STACK_WORK_FULL}"
    displayName: Prepare directories
  - task: Cache@2
    displayName: Cache STACK_ROOT
    inputs:
      key: '"${{ parameters.name }}" | $(STACK_ROOT) | "$(RESOLVER) - $(Build.SourceBranch)"'
      path: "$(STACK_ROOT)"
      restoreKeys: |
        "${{ parameters.name }}" | $(STACK_ROOT) | "$(RESOLVER) - $(Build.SourceBranch)"
        "${{ parameters.name }}" | $(STACK_ROOT) | "$(RESOLVER) - refs/heads/master"
  - task: Cache@2
    displayName: Cache STACK_WORK
    inputs:
      key: '"${{ parameters.name }}" | $(STACK_WORK_FULL) | "$(RESOLVER) - $(Build.SourceBranch)"'
      path: "$(STACK_WORK_FULL)"
      restoreKeys: |
        "${{ parameters.name }}" | $(STACK_WORK_FULL) | "$(RESOLVER) - $(Build.SourceBranch)"
        "${{ parameters.name }}" | $(STACK_WORK_FULL) | "$(RESOLVER) - refs/heads/master"
  - task: Bash@3
    displayName: Download tools
    inputs:
      targetType: 'inline'
      script: |
        # Install stack
        curl -sSkL https://www.stackage.org/stack/windows-x86_64 -o stack.zip
        7z x stack.zip stack.exe -aoa
        # Script for restoring source files modification time from commit to avoid recompilation.
        curl -sSkL https://gist.githubusercontent.com/lehins/fd36a8cc8bf853173437b17f6b6426ad/raw/d9ddb32cac2f0dc6800be4fa54d450f0dcda6c60/git-modtime.hs -o git-modtime.hs
  - task: Bash@3
    displayName: Test on ${{parameters.os}}'
    env:
      ARGS: "--resolver $(RESOLVER)"
      BUILD_ARGS: "-j 2 --no-terminal --bench --no-run-benchmarks --haddock --no-haddock-deps"
    inputs:
      targetType: 'inline'
      script: |
        # stack script --resolver ${RESOLVER} git-modtime.hs
        stack "${ARGS}" test massiv-io:tests "${BUILD_ARGS}"
        stack "${ARGS}" test massiv-io:doctests "${BUILD_ARGS}"
